version: "3.8"
networks:
  jedi:

services:
  app:
    container_name: manager-app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6280:8080"
    networks:
      - jedi

  db:
    container_name: manager-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: tasks
    networks:
      - jedi

